version: '3.7'

services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:12.1.0.2
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=123456a@
      - ORACLE_USER=caoquyen
    volumes:
      - oracle_data:/opt/oracle/oradata
volumes:
  oracle_data: